USE master
GO
IF EXISTS (SELECT * FROM sysdatabases WHERE name='AbbettHotels')
		DROP DATABASE AbbettHotels
GO

CREATE DATABASE AbbettHotels
GO

USE AbbettHotels
GO

CREATE TABLE Customer (
	CustomerID INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
	CompanyName NVARCHAR (40) NOT NULL ,
	ContactName NVARCHAR (30) NULL ,
	ContactTitle NVARCHAR (30) NULL ,
	Address NVARCHAR (60) NULL ,
	City NVARCHAR (15) NULL ,
	Region NVARCHAR (15) NULL ,
	PostalCode NVARCHAR (10) NULL ,
	Country NVARCHAR (15) NULL ,
	Phone NVARCHAR (24) NULL ,
	Fax NVARCHAR (24) NULL 
)
GO

CREATE TABLE Reservation (
	ReservationID INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
	CustomerID INT NOT NULL FOREIGN KEY REFERENCES Customer(CustomerID),
	BookingDate DATE NOT NULL,
	Checkin DATE NOT NULL,
	Checkout DATE NOT NULL,
	)
GO

CREATE TABLE RoomCategory (
	CategoryID INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
	CategoryName NVARCHAR (20) NOT NULL,
	[Description] NVARCHAR (40) NOT NULL
	)
GO

CREATE TABLE Room (
	RoomID INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
	RoomNumber INT NOT NULL,
	CategoryID INT NOT NULL FOREIGN KEY REFERENCES RoomCategory(CategoryID),
	RoomRate MONEY NULL,
	FloorNumber INT NOT NULL,
	OccupancyLimit INT NOT NULL
	)
GO

CREATE TABLE Amenity (
	AmenityID INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
	AmenityName VARCHAR(20) NOT NULL,
	[Description] VARCHAR(60) NULL
	)
GO

CREATE TABLE AddOn (
	AddOnID INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
	AddOnName VARCHAR(20) NOT NULL,
	Price MONEY NULL
	)
GO

CREATE TABLE ReservationAddOn (
	ReservationID INT NOT NULL FOREIGN KEY REFERENCES Reservation(ReservationID),
	AddOnID INT NOT NULL FOREIGN KEY REFERENCES AddOn(AddOnID)
	)
GO

CREATE TABLE RoomAmenity (
	RoomID INT NOT NULL FOREIGN KEY REFERENCES Room(RoomID),
	AmenityID INT NOT NULL FOREIGN KEY REFERENCES Amenity(AmenityID)
	)
GO

CREATE TABLE Guest (
	GuestID INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
	RoomID INT NOT NULL FOREIGN KEY REFERENCES Room(RoomID),
	ReservationID INT NOT NULL FOREIGN KEY REFERENCES Reservation(ReservationID),
	GuestName NVARCHAR(30) NOT NULL,
	GuestAge INT NOT NULL
	)
GO

CREATE TABLE PromotionCode (
	PromotionID INT IDENTITY (1,1) NOT NULL PRIMARY KEY,
	PromotionDetails NVARCHAR (40) NOT NULL
	)
GO
	

CREATE TABLE ReservationDetails (
	ReservationID INT NOT NULL FOREIGN KEY REFERENCES Reservation(ReservationID),
	RoomID INT NOT NULL FOREIGN KEY REFERENCES Room(RoomID),
	RoomRate MONEY NULL,
	TaxRate MONEY NULL,
	Total MONEY NULL,
	PromotionID INT NOT NULL FOREIGN KEY REFERENCES PromotionCode(PromotionID)
	)
GO
